version: "3.8"
services:
  rabbitmq1:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq_ha
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_NODE_PORT=5672
    volumes:
      - ./config:/config
      - ./defs/def.json:/etc/rabbitmq/definitions.json:ro
      - ./defs/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./defs/hosts:/etc/hosts

    ports:
      - 15672:15672
      - 5672:5672
      - 4369:4369
      - 25672:25672
    # networks:
      # - rabbitmq-net


  # rabbitmq2:
    # image: rabbitmq:3.10.7-management
    # hostname: rabbitmq2
    # environment:
      # - RABBITMQ_CONFIG_FILE=/config/rabbitmq_ha
      # - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      # - RABBITMQ_NODE_PORT=5672
    # volumes:
      # - ./config:/config
      # - ./defs/def.json:/etc/rabbitmq/definitions.json:ro
      # - ./defs/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

    # networks:
      # - rabbitmq-net

# networks:
    # rabbitmq-net:
        # driver: bridge
