---
- name: Install Clickhouse on CentOS Stream 9
  hosts: clickhouse
  become: true
  tags: clickhouse

  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - name: Get clickhouse distrib MAIN
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "/tmp/{{ item }}-{{ clickhouse_version }}.rpm"
            mode: '0644'
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib rescue
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "/tmp/{{ item }}-{{ clickhouse_version }}.rpm"
            mode: '0644'
          with_items: "{{ clickhouse_packages }}"

    - name: Update yum cache
      ansible.builtin.dnf:
        update_cache: true

    - name: Install clickhouse packages
      ansible.builtin.dnf:
        name:
          - /tmp/clickhouse-common-static-{{ clickhouse_version }}.rpm
          - /tmp/clickhouse-client-{{ clickhouse_version }}.rpm
          - /tmp/clickhouse-server-{{ clickhouse_version }}.rpm
        disable_gpg_check: true
        state: present
      notify: Start clickhouse service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector on CentOS Stream 9
  hosts: vector
  become: true
  tags: vector

  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "/tmp/vector-{{ vector_version }}.rpm"
        mode: '0644'

    - name: Update yum cache
      ansible.builtin.dnf:
        update_cache: true


    - name: Install vector

      ansible.builtin.dnf:
        disable_gpg_check: true
        name: "/tmp/vector-{{ vector_version }}.rpm"
        state: present

    - name: Deploy vector configuration
      ansible.builtin.template:
        src: templates/vector.yaml.j2
        dest: "{{ vector_config_path }}"
        mode: '0644'
      notify: Start vector service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

- name: Install nginx on CentOS Stream 9
  hosts: lighthouse
  become: true
  tags: nginx

  handlers:
    - name: Start Nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Reload Nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: reloaded

  tasks:
    - name: NGINX | Install epel-release
      become: true
      ansible.builtin.dnf:
        name: epel-release
        state: present
    - name: NGINX | Install nginx
      become: true
      ansible.builtin.dnf:
        name: nginx
        state: present
      notify: Start Nginx
    - name: NGINX | Create config
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify: Reload Nginx


- name: Install LightHouse on CentOS Stream 9
  hosts: lighthouse
  become: true
  tags: lighthouse

  handlers:
    - name: Reload Nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: reloaded

  pre_tasks:
    - name: Lighthouse | install git
      become: true
      ansible.builtin.dnf:
        name: git
        state: present

  tasks:
    - name: Lighthouse | copy from git
      ansible.builtin.git:
        repo: "{{ lighthouse_source }}"
        version: master
        dest: "{{ lighthouse_loc_dir }}"

    - name: Lighthouse | Create config
      become: true
      ansible.builtin.template:
        src: templates/lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: '0644'
      notify: Reload Nginx

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
