apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-multi-app
  template:
    metadata:
      labels:
        app: nginx-multi-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: nginx-port
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080" 
        ports:
        - containerPort: 8080
          name: mtool-port
