##Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-depl
  labels:
    app: nginx-app-d
#  namespace: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app-c
        image: cr.yandex/crpefno6d2dqdrf96gqk/nginx-app:v0.0.2
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
#      imagePullSecrets:
#        - name: cr.ya.pull

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
#  namespace: test-app
spec:
  selector:
    app: nginx-app
  ports:
  - name: nginx-app-port
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-app-ingress
#  namespace: test-app
  annotations:
#    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: netology.local
    http: 
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx-app-service
            port:
#              name: test-nginx-port
               number: 80
  - host: www.knit-tale.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-app-service
            port:
              number: 80
  - http: 
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx-app-service
            port:
#              name: test-nginx-port
               number: 80