apiVersion: v1
kind: Pod
metadata:
  name: network-multitool
  labels:
      app: network-multitool
spec:
  containers:
  - name: network-multitool
    image: wbitt/network-multitool
    imagePullPolicy: IfNotPresent