apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  ports:
   - name: nginx
     port: 10080
     protocol: TCP
     targetPort: 80
   - name: mt-http
     port: 1180
     protocol: TCP
     targetPort: 1180
   - name: mt-https
     port: 11443
     protocol: TCP
     targetPort: 11443


  selector:
     app: nginx-multitool
