version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zaq12WSX
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
      - "8080:8080"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
