apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: {{ .Values.application.backend.replicas}}
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: multitool
        image: {{ .Values.application.version}}
        env:
        - name: HTTP_PORT
          value: "8080" 
        ports:
        - containerPort: {{ .Values.application.backend.port}}
          name: mtool-port
