apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: mtool-http
    port: {{ .Values.application.frontend.port}}
    protocol: TCP

  selector:
    app: frontend-app
  type: ClusterIP