apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-sc # ДОПОЛНИТЕ: Имя StorageClass
provisioner: kubernetes.io/no-provisioner # ИНФОРМАЦИЯ: Нет автоматического развёртывания
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-sc # ДОПОЛНИТЕ: Имя PVC
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi # ДОПОЛНИТЕ: Какой объем хранилища вы хотите передать в контейнер. Должно быть меньше или равно параметру storage из PV
  storageClassName: test-sc # ДОПОЛНИТЕ: Имя StorageClass. Должно совпадать с объявленным ранее
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1 # ЗАДАНИЕ: Укажите количество реплик
  selector:
    matchLabels:
      app: data-exchange-pvc-sc # ДОПОЛНИТЕ: Метка для селектора
  template:
    metadata:
      labels:
        app: data-exchange-pvc-sc # ПОВТОРИТЕ: Метка из selector.matchLabels
    spec:
      containers:
      - name: busybox-sc # ДОПОЛНИТЕ: Имя первого контейнера
        image: busybox
        command: ["/bin/sh", "-c"] 
        args: ["mkdir -p /tmpvol && while true; do echo $(date) >> /tmpvol/exchange; sleep 5; done"] # КЛЮЧЕВОЕ: Команда записи данных в файл в директории из секции volumeMounts контейнера 
        volumeMounts:
        - name: exchange-vol # ДОПОЛНИТЕ: Имя монтируемого раздела. Должно совпадать с именем хранилища, объявленного на уровне пода
          mountPath: /tmpvol # КЛЮЧЕВОЕ: Путь монтирования хранилища внутри контейнера 1
      - name: multitool-sc # ДОПОЛНИТЕ: Имя второго контейнера
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args: ["mkdir -p /tmpvol && tail -f /tmpvol/exchange"] # КЛЮЧЕВОЕ: Команда для чтения данных из файла, расположенного в директории, указанной в volumeMounts контейнера
        volumeMounts:
        - name: exchange-vol # ДОПОЛНИТЕ: Имя монтируемого раздела. Должно совпадать с именем хранилища, объявленного на уровне пода
          mountPath: /tmpvol # КЛЮЧЕВОЕ: Путь монтирования хранилища внутри контейнера 2
      volumes:
      - name: exchange-vol # ДОПОЛНИТЕ: Имя монтируемого раздела хранилища
        persistentVolumeClaim:
          claimName: test-pvc-sc # КЛЮЧЕВОЕ: Совпадает с именем PVC объявленного ранее